// Copyright (c) Lanre. All rights reserved.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.InvalidCredentialsErrorMessage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.IncludeWindowsGroups")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1214:Readonly fields should appear before non-readonly fields", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.WindowsAuthenticationSchemeName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.AutomaticRedirectAfterSignOut")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.ShowLogoutPrompt")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.RememberMeLoginDuration")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.AllowRememberLogin")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Accounts.AccountOptions.AllowLocalLogin")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Consent.ConsentOptions.EnableOfflineAccess")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Consent.ConsentOptions.OfflineAccessDisplayName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Consent.ConsentOptions.OfflineAccessDescription")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1214:Readonly fields should appear before non-readonly fields", Justification = "Reviewed.", Scope = "member", Target = "~F:Clients.IdentityServer.Models.Consent.ConsentOptions.MustChooseOneErrorMessage")]
